package no.nav.dokdistsentralprint.qdist009.util;

import lombok.Getter;

@Getter
// Listen følger ISO 3166-1 og er hentet fra https://no.wikipedia.org/wiki/ISO_3166-1
public enum Landkoder {
    AF("AF","Afghanistan"),
    AL("AL","Albania"),
    DZ("DZ","Algerie"),
    AS("AS","Amerikansk Samoa"),
    AD("AD","Andorra"),
    AO("AO","Angola"),
    AI("AI","Anguilla"),
    AQ("AQ","Antarktis"),
    AG("AG","Antigua og Barbuda"),
    AR("AR","Argentina"),
    AM("AM","Armenia"),
    AW("AW","Aruba"),
    AZ("AZ","Aserbajdsjan"),
    AU("AU","Australia"),
    BS("BS","Bahamas"),
    BH("BH","Bahrain"),
    BD("BD","Bangladesh"),
    BB("BB","Barbados"),
    BE("BE","Belgia"),
    BZ("BZ","Belize"),
    BJ("BJ","Benin"),
    BM("BM","Bermuda"),
    BT("BT","Bhutan"),
    BO("BO","Bolivia"),
    BQ("BQ","Karibisk Nederland Bonaire,"),
    BA("BA","Bosnia-Hercegovina"),
    BW("BW","Botswana"),
    BV("BV","Bouvetøya"),
    BR("BR","Brasil"),
    BN("BN","Brunei"),
    BG("BG","Bulgaria"),
    BF("BF","Burkina Faso"),
    BI("BI","Burundi"),
    CA("CA","Canada"),
    KY("KY","Caymanøyene"),
    CL("CL","Chile"),
    CX("CX","Christmasøya"),
    CO("CO","Colombia"),
    CK("CK","Cookøyene"),
    CR("CR","Costa Rica"),
    CU("CU","Cuba"),
    CW("CW","Curaçao"),
    DK("DK","Danmark"),
    AE("AE","De forente arabiske emirater"),
    TF("TF","De franske sørterritorier"),
    PS("PS","Palestina De"),
    DO("DO","Den dominikanske republikk"),
    CF("CF","Den sentralafrikanske republikk"),
    IO("IO","Det britiske territoriet i Indiahavet"),
    DJ("DJ","Djibouti"),
    DM("DM","Dominica"),
    EC("EC","Ecuador"),
    EG("EG","Egypt"),
    GQ("GQ","Ekvatorial-Guinea"),
    CI("CI","Elfenbenskysten"),
    SV("SV","El Salvador"),
    ER("ER","Eritrea"),
    EE("EE","Estland"),
    ET("ET","Etiopia"),
    FK("FK","Falklandsøyene"),
    FJ("FJ","Fiji"),
    PH("PH","Filippinene"),
    FI("FI","Finland"),
    FR("FR","Frankrike"),
    GF("GF","Fransk Guyana"),
    PF("PF","Fransk Polynesia"),
    FO("FO","Færøyene"),
    GA("GA","Gabon"),
    GM("GM","Gambia"),
    GE("GE","Georgia"),
    GH("GH","Ghana"),
    GI("GI","Gibraltar"),
    GD("GD","Grenada"),
    GL("GL","Grønland"),
    GP("GP","Guadeloupe"),
    GU("GU","Guam"),
    GT("GT","Guatemala"),
    GG("GG","Guernsey"),
    GN("GN","Guinea"),
    GW("GW","Guinea-Bissau"),
    GY("GY","Guyana"),
    HT("HT","Haiti"),
    HM("HM","Heard- og McDonaldøyene"),
    GR("GR","Hellas"),
    HN("HN","Honduras"),
    HK("HK","Hongkong"),
    BY("BY","Hviterussland"),
    IN("IN","India"),
    ID("ID","Indonesia"),
    IQ("IQ","Irak"),
    IR("IR","Iran"),
    IE("IE","Irland"),
    IS("IS","Island"),
    IL("IL","Israel"),
    IT("IT","Italia"),
    JM("JM","Jamaica"),
    JP("JP","Japan"),
    YE("YE","Jemen"),
    JE("JE","Jersey"),
    VI("VI","De amerikanske Jomfruøyer"),
    VG("VG","De britiske Jomfruøyer"),
    JO("JO","Jordan"),
    KH("KH","Kambodsja"),
    CM("CM","Kamerun"),
    CV("CV","Kapp Verde"),
    KZ("KZ","Kasakhstan"),
    KE("KE","Kenya"),
    CN("CN","Kina"),
    KG("KG","Kirgisistan"),
    KI("KI","Kiribati"),
    CC("CC","Kokosøyene"),
    KM("KM","Komorene"),
    CD("CD","Den demokratiske republikken Kongo"),
    CG("CG","Republikken Kongo"),
    HR("HR","Kroatia"),
    KW("KW","Kuwait"),
    CY("CY","Kypros"),
    LA("LA","Laos"),
    LV("LV","Latvia"),
    LS("LS","Lesotho"),
    LB("LB","Libanon"),
    LR("LR","Liberia"),
    LY("LY","Libya"),
    LI("LI","Liechtenstein"),
    LT("LT","Litauen"),
    LU("LU","Luxembourg"),
    MO("MO","Macao"),
    MG("MG","Madagaskar"),
    MK("MK","Nord-Makedonia"),
    MW("MW","Malawi"),
    MY("MY","Malaysia"),
    MV("MV","Maldivene"),
    ML("ML","Mali"),
    MT("MT","Malta"),
    IM("IM","Man"),
    MA("MA","Marokko"),
    MH("MH","Marshalløyene"),
    MQ("MQ","Martinique"),
    MR("MR","Mauritania"),
    MU("MU","Mauritius"),
    YT("YT","Mayotte"),
    MX("MX","Mexico"),
    FM("FM","Mikronesiaføderasjonen"),
    MD("MD","Moldova"),
    MC("MC","Monaco"),
    MN("MN","Mongolia"),
    ME("ME","Montenegro"),
    MS("MS","Montserrat"),
    MZ("MZ","Mosambik"),
    MM("MM","Myanmar"),
    NA("NA","Namibia"),
    NR("NR","Nauru"),
    NP("NP","Nepal"),
    NL("NL","Nederland"),
    NZ("NZ","New Zealand"),
    NI("NI","Nicaragua"),
    NE("NE","Niger"),
    NG("NG","Nigeria"),
    NU("NU","Niue"),
    KP("KP","Nord-Korea"),
    MP("MP","Nord-Marianene"),
    NF("NF","Norfolkøya"),
    NO("NO","Norge"),
    NC("NC","Ny-Caledonia"),
    OM("OM","Oman"),
    PK("PK","Pakistan"),
    PW("PW","Palau"),
    PA("PA","Panama"),
    PG("PG","Papua Ny-Guinea"),
    PY("PY","Paraguay"),
    PE("PE","Peru"),
    PN("PN","Pitcairnøyene"),
    PL("PL","Polen"),
    PT("PT","Portugal"),
    PR("PR","Puerto Rico"),
    QA("QA","Qatar"),
    RE("RE","Réunion"),
    RO("RO","Romania"),
    RU("RU","Russland"),
    RW("RW","Rwanda"),
    BL("BL","Saint-Barthélemy"),
    SH("SH","St. Helena, Ascension og Tristan da Cunha"),
    KN("KN","Saint Kitts og Nevis"),
    LC("LC","Saint Lucia"),
    MF("MF","Saint-Martin"),
    PM("PM","Saint-Pierre og Miquelon"),
    VC("VC","Saint Vincent og Grenadinene"),
    SB("SB","Salomonøyene"),
    WS("WS","Samoa"),
    SM("SM","San Marino"),
    ST("ST","São Tomé og Príncipe"),
    SA("SA","Saudi-Arabia"),
    SN("SN","Senegal"),
    RS("RS","Serbia"),
    SC("SC","Seychellene"),
    SL("SL","Sierra Leone"),
    SG("SG","Singapore"),
    SX("SX","Sint Maarten"),
    SK("SK","Slovakia"),
    SI("SI","Slovenia"),
    SO("SO","Somalia"),
    ES("ES","Spania"),
    LK("LK","Sri Lanka"),
    GB("GB","Storbritannia"),
    SD("SD","Sudan"),
    SR("SR","Surinam"),
    SJ("SJ","Svalbard og Jan Mayen"),
    CH("CH","Sveits"),
    SE("SE","Sverige"),
    SZ("SZ","Swaziland"),
    SY("SY","Syria"),
    ZA("ZA","Sør-Afrika"),
    GS("GS","Sør-Georgia og Sør-Sandwichøyene"),
    KR("KR","Sør-Korea"),
    SS("SS","Sør-Sudan"),
    TJ("TJ","Tadsjikistan"),
    TW("TW","Taiwan"),
    TZ("TZ","Tanzania"),
    TH("TH","Thailand"),
    TG("TG","Togo"),
    TK("TK","Tokelau"),
    TO("TO","Tonga"),
    TT("TT","Trinidad og Tobago"),
    TD("TD","Tsjad"),
    CZ("CZ","Tsjekkia"),
    TN("TN","Tunisia"),
    TM("TM","Turkmenistan"),
    TC("TC","Turks- og Caicosøyene"),
    TV("TV","Tuvalu"),
    TR("TR","Tyrkia"),
    DE("DE","Tyskland"),
    UG("UG","Uganda"),
    UA("UA","Ukraina"),
    HU("HU","Ungarn"),
    UY("UY","Uruguay"),
    US("US","USA"),
    UM("UM","USAs ytre småøyer"),
    UZ("UZ","Usbekistan"),
    VU("VU","Vanuatu"),
    VA("VA","Vatikanstaten"),
    VE("VE","Venezuela"),
    EH("EH","Vest-Sahara"),
    VN("VN","Vietnam"),
    WF("WF","Wallis og Futuna"),
    ZM("ZM","Zambia"),
    ZW("ZW","Zimbabwe"),
    AT("AT","Østerrike"),
    TL("TL","Øst-Timor"),
    AX("AX","Åland");

    private final String landkode;
    private final String landnavn;

    Landkoder(String landkode, String landnavn) {
        this.landkode = landkode;
        this.landnavn = landnavn;
    }
}
