<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- I forbindelse med flytting av bdist002 til Nais har XSD-skjemaet blitt forenklet og tilpasset
	at RapportTypeKode alltid har verdien 'Mailpiece'.
	- Fjern verdiene 'Printoppdrag' og 'Dokument' fra RapportTypeKode
	- Fjern verdiene 'SPORDOK_RELEASE', 'ETTERBEHANDLER', 'POSTLAGT', 'MOTTATT' fra LePuKode
	- Fjern alt tilknyttet PO (PoStatus, PoRapport)
	- Fjern extensions og legg inn attributtene direkte
	-->

	<xs:simpleType name="RapportTypeKode">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Mailpiece"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="StatusKode">
		<xs:restriction base="xs:string">
			<xs:enumeration value="OK"/>
			<xs:enumeration value="FEIL"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="LePuKode">
		<xs:restriction base="xs:string">
			<xs:enumeration value="RETURPOST"/>
			<xs:enumeration value="KONVOLUTTERT"/>
			<xs:enumeration value="MAILPIECE_MOTTAK"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="TimestampType">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d{2}/\d{2}/\d{4}\s\d{2}:\d{2}:\d{2}"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="Status">
		<xs:complexType>
			<xs:attribute name="Id" type="xs:string" use="required"/>
			<xs:attribute name="Status" type="StatusKode" use="required"/>
			<xs:attribute name="LePu" type="LePuKode" use="required"/>
			<xs:attribute name="Tidspunkt" type="TimestampType" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="Rapport">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Status"/>
			</xs:sequence>
			<xs:attribute name="Id" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="StatusRapport">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Rapport" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="Type" type="RapportTypeKode" use="required"/>
		</xs:complexType>
	</xs:element>

</xs:schema>